name: Friendly CI

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "Hello from GitHub Actions!"

    - name: List files in repo
      run: ls -la
